version: '3.9'
services:
  web-app:
    init: true
    image: web-app
    container_name: web-app
    build:
      context: ../../
      dockerfile: ./docker/build/Dockerfile.client.dev
    volumes:
      - type: bind
        source: ../../@app/client
        target: /var/www/@app/client
      - type: volume
        target: /var/www/@app/client/node_modules
      - type: bind
        source: ../../@app/client/vite.config.ts
        target: /var/www/@app/client/vite.config.ts
    ports:
      - 3000:3000

  api:
    image: api
    container_name: api
    build:
      context: ../../
      dockerfile: ./docker/build/Dockerfile.server.dev
    volumes:
      - type: bind
        source: ../../@app/server
        target: /var/www/@app/server
      - type: volume
        target: /var/www/@app/server/node_modules
    ports:
      - 4000:4000
