version: '3.9'
name: monorepo_dev
services:
  web-app:
    init: true
    image: img_monorepo-web-app_dev
    container_name: web-app
    build:
      context: ../../
      dockerfile: ./docker/build/Dockerfile.client.dev
    volumes:
      - type: bind
        source: ../../@app/client
        target: /var/www/@app/client
      - type: volume
        target: /var/www/@app/client/node_modules
      - type: bind
        source: ../../@app/client/vite.config.ts
        target: /var/www/@app/client/vite.config.ts
    environment:
      - NETWORK_ENV=docker
    ports:
      - 8080:8080
    networks:
      - frontend

  api:
    image: img_morepo-api_dev
    container_name: api
    build:
      context: ../../
      dockerfile: ./docker/build/Dockerfile.server.dev
    volumes:
      - type: bind
        source: ../../@app/server
        target: /var/www/@app/server
    ports:
      - 4000:4000
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: net_morepo-frontend_dev
  backend:
    name: net_monorepo-backend_dev
